# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# this runs unit tests for pcf and publishes the test result in to azure
# to use this feature you need to using jest-junit
# follow the link here https://blog.johnnyreilly.com/2020/12/30/azure-pipelines-meet-jest

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run refreshTypes
    npm run build
  displayName: 'npm install and build'

- task: Npm@1  
  inputs:
    command: 'custom'
    customCommand: 'run test:ci'
  displayName: 'Running Test'

- task: PublishTestResults@2
  displayName: 'supply npm test results to pipelines'
  condition: succeededOrFailed() # because otherwise we won't know what tests failed
  inputs:
    testResultsFiles: 'CustomerAddressMapper/__tests__/junit.xml'


